Repository tommerw/StockProject, pull requests merged in 2020-10, with the labels that each got.

#3 Stock symbol not exist for historic endpoint
  myapp/exceptions/stock_service.py
  myapp/static/css/exception.css
  myapp/stock_api.py
  myapp/templates/exception.html
  myapp/views.py
Labels: bug

#4 Redirecting unknown URLs
  myapp/urls.py
  myrails/urls.py
  myrails/views.py
Labels: bug

#7 User password change form
  myapp/templates/base.html
  myapp/templates/password_change.html
  myapp/urls.py
  myapp/views.py
Labels: enhancement

#6 Favorite stocks and user profile improvements
  myapp/admin.py
  myapp/models.py
  myapp/templates/base.html
  myapp/templates/index.html
  myapp/templates/login.html
  myapp/templates/profile.html
  myapp/templates/single_stock.html
  myapp/templates/watchlist.html
  myapp/urls.py
  myapp/views.py
Labels: enhancement

#14 Add missing profile migrations
  .gitignore
  myapp/migrations/0004_profile.py
Labels: documentation, invalid

#24 Adding Unit testing for stock watchlist model and authentication views
  myapp/tests/test_models.py
  myapp/tests/test_views.py
Labels: documentation, tests

#25 adding pagination to stocks in home page
  .gitignore
  myapp/stock_api.py
  myapp/templates/base.html
  myapp/templates/index.html
  myapp/templatetags/__init__.py
  myapp/templatetags/myapp_tags.py
  myapp/views.py
Labels: new feature

#22 Stock watchlist improvements
  myapp/templates/base.html
  myapp/templates/index.html
  myapp/templates/single_stock.html
  myapp/templates/watchlist.html
  myapp/views.py
Labels: bug, enhancement

#27 Profile object not found for old users
  myapp/views.py
Labels: bug

#16 Adding Unit testing for "single_stock" and "single_stock_historic" views
  myapp/tests/test_stock_api.py
  myapp/tests/test_views.py
Labels: tests

#30 adding editorconfig file to standradizing code-style
  .editorconfig
Labels: enhancement

#28 fix on the bug of pagination indices isn't properly viewed
  myapp/templates/index.html
  myapp/templatetags/myapp_tags.py
Labels: bug

#23 User account forms improvements
  myapp/forms.py
  myapp/templates/login.html
  myapp/templates/password_change.html
  myapp/templates/register.html
  myapp/tests/test_forms.py
  myapp/views.py
Labels: bug, enhancement
