Repository tommerw/StockProject, pull requests merged in 2020-11, with the labels that each got.

#32 Adding adjustable time range to single stock chart
  myapp/exceptions/stock_service.py
  myapp/stock_api.py
  myapp/templates/single_stock.html
  myapp/tests/test_stock_api.py
  myapp/urls.py
  myapp/views.py
  myrails/test/test_views.py
Labels: enhancement, tests

#38 Time Range Unit Test Fix
  myapp/tests/test_stock_api.py
Labels: invalid, tests

#39 adding deploy.sh file for deploying the app.
  deploy.sh
Labels: enhancement

#35 Adding `is_needed` Stock object boolean flag for db cleanup
  myapp/models.py
  myapp/tests/test_models.py
Labels: enhancement

#36 Refactoring comparison feature
  .editorconfig
  myapp/static/js/myapp/single_stock.js
  myapp/stock_api.py
  myapp/templates/base.html
  myapp/templates/single_stock.html
  myapp/tests/test_stock_api.py
  myapp/tests/test_views.py
  myapp/urls.py
  myapp/views.py
Labels: enhancement

#40 Fix Time Range Unit Testing 'days_since_last_result'
  myapp/tests/test_stock_api.py
Labels: invalid, tests

#41 Adding stocks not in db to watchlist
  myapp/models.py
  myapp/tests/test_models.py
  myapp/views.py
Labels: enhancement

#43 refactoring comparison to compare more than two stocks
  myapp/static/js/myapp/single_stock.js
  myapp/templates/single_stock.html
Labels: refactors

#42 refactoring the search functionality
  myapp/static/js/myapp/index.js
  myapp/static/js/myapp/single_stock.js
  myapp/stock_api.py
  myapp/templates/index.html
  myapp/templates/single_stock.html
  myapp/tests/test_stock_api.py
  myapp/tests/test_views.py
  myapp/views.py
  myrails/urls.py
Labels: refactors

#44 Improving Stock `is_needed` SQL Query
  myapp/models.py
Labels: enhancement

#46 fix for the bug for search functionality
  myapp/static/js/myapp/index.js
  myapp/views.py
Labels: bug

#49 Adding Notification URLField
  myapp/migrations/0007_notification_link.py
  myapp/migrations/0008_auto_20201114_2036.py
  myapp/models.py
Labels: enhancement, notification feature

#50 Notification `is_read` bool field
  myapp/migrations/0009_notification_is_read.py
  myapp/models.py
Labels: enhancement, notification feature

#47 changing the design of pagination
  myapp/templates/index.html
Labels: refactors

#51 Refactoring the watchlist model for compatibility with requirements of notifications-rules
  myapp/migrations/0006_auto_20201115_1228.py
  myapp/models.py
  myapp/tests/test_models.py
  myapp/tests/test_stock_api.py
  myapp/tests/test_views.py
Labels: refactors

#37 Migration to MySQL Database
  .gitignore
  myrails/configuration/Readme.md
  myrails/configuration/__init__.py
  myrails/configuration/config.py
  myrails/configuration/dev_example.cfg
  myrails/settings.py
  requirements.txt
Labels: enhancement

#54 adding abstracted notification rules models
  myapp/admin.py
  myapp/migrations/0007_auto_20201114_1423.py
  myapp/migrations/0008_auto_20201114_1533.py
  myapp/migrations/0009_merge_20201115_1444.py
  myapp/migrations/0010_auto_20201115_1521.py
  myapp/migrations/0011_merge_20201115_2020.py
  myapp/migrations/0012_auto_20201115_2239.py
  myapp/migrations/0013_merge_20201117_1908.py
  myapp/models.py
  myapp/sub_models/__init__.py
  myapp/sub_models/notification_rules.py
  myapp/tests/test_models.py
Labels: enhancement

#60 Notification rules functionality
  myapp/admin.py
  myapp/migrations/0012_auto_20201115_2239.py
  myapp/migrations/0012_merge_20201117_1557.py
  myapp/migrations/0013_auto_20201117_1557.py
  myapp/migrations/0014_delete_activityperiodrule.py
  myapp/migrations/0015_auto_20201118_1118.py
  myapp/migrations/0016_recommendationanalystrule_recommenders_percentage.py
  myapp/migrations/0017_auto_20201118_1505.py
  myapp/migrations/0018_auto_20201118_1533.py
  myapp/migrations/0019_auto_20201118_1824.py
  myapp/models.py
  myapp/scheduler/notification_updater.py
  myapp/scheduler/scheduler.py
  myapp/stock_api.py
  myapp/sub_models/notification_rules.py
  myapp/sub_models/test_models.py
  myapp/tests/test_models.py
  myapp/tests/test_scheduler.py
Labels: enhancement

#65 Displaying and managing notifications on the frontend
  myapp/models.py
  myapp/static/js/myapp/base.js
  myapp/templates/base.html
  myapp/tests/test_views.py
  myapp/urls.py
  myapp/views.py
Labels: enhancement, notification feature

#70 Unit testing for notification functionality
  myapp/admin.py
  myapp/migrations/0020_auto_20201122_1725.py
  myapp/models.py
  myapp/scheduler/notification_rules_handler.py
  myapp/scheduler/scheduler.py
  myapp/scheduler/tests/__init__.py
  myapp/scheduler/tests/test_notification_handler_updater.py
  myapp/scheduler/tests/test_scheduler.py
  myapp/scheduler/tests/test_stock_api_update.py
  myapp/sub_models/notification_rules_models.py
  myapp/sub_models/tests/test_models.py
  myapp/tests/test_scheduler.py
Labels: tests

#71 adding Buy and sell functionality
  myapp/exceptions/stock_service.py
  myapp/migrations/0007_auto_20201123_1920.py
  myapp/models.py
  myapp/scheduler/stock_api_update.py
  myapp/urls.py
  myapp/views.py
Labels: enhancement

#72 Managing Notification Rules on the Frontend
  myapp/forms.py
  myapp/static/js/myapp/base.js
  myapp/static/js/myapp/single_stock.js
  myapp/sub_models/notification_rules_models.py
  myapp/templates/add_rule.html
  myapp/templates/base.html
  myapp/templates/edit_rule.html
  myapp/templates/single_stock.html
  myapp/templates/subtemplate/list_rules.html
  myapp/templates/watchlist.html
  myapp/urls.py
  myapp/views.py
  myrails/settings.py
  requirements.txt
Labels: enhancement, notification feature

#74 Fixing Unread Notifications Count Bug
  myapp/static/js/myapp/base.js
Labels: bug, notification feature

#66 Encrypting the Production Server Configuration File
  deploy.sh
  myrails/configuration/Readme.md
  myrails/configuration/prod.encrypted
  myrails/configuration/public_key.pem
Labels: enhancement

#69 User notifications
  myapp/admin.py
  myapp/forms.py
  myapp/migrations/0006_notification.py
  myapp/migrations/0007_auto_20201114_1423.py
  myapp/migrations/0007_notification_link.py
  myapp/migrations/0008_auto_20201114_1533.py
  myapp/migrations/0008_auto_20201114_2036.py
  myapp/migrations/0009_merge_20201115_1444.py
  myapp/migrations/0009_notification_is_read.py
  myapp/migrations/0010_auto_20201115_1521.py
  myapp/migrations/0010_merge_20201117_1547.py
  myapp/migrations/0011_merge_20201115_2020.py
  myapp/migrations/0012_merge_20201117_1557.py
  myapp/migrations/0013_auto_20201117_1557.py
  myapp/migrations/0014_delete_activityperiodrule.py
  myapp/migrations/0015_auto_20201118_1118.py
  myapp/migrations/0016_recommendationanalystrule_recommenders_percentage.py
  myapp/migrations/0017_auto_20201118_1505.py
  myapp/migrations/0018_auto_20201118_1533.py
  myapp/migrations/0019_auto_20201118_1824.py
  myapp/migrations/0020_auto_20201122_1725.py
  myapp/models.py
  myapp/scheduler/notification_rules_handler.py
  myapp/scheduler/scheduler.py
  myapp/scheduler/stock_api_update.py
  myapp/scheduler/tests/__init__.py
  myapp/scheduler/tests/test_notification_handler_updater.py
  myapp/scheduler/tests/test_scheduler.py
  myapp/scheduler/tests/test_stock_api_update.py
  myapp/static/js/myapp/base.js
  myapp/static/js/myapp/single_stock.js
  myapp/stock_api.py
  myapp/sub_models/__init__.py
  myapp/sub_models/notification_rules_models.py
  myapp/sub_models/tests/__init__.py
  myapp/sub_models/tests/test_models.py
  myapp/templates/add_rule.html
  myapp/templates/base.html
  myapp/templates/edit_rule.html
  myapp/templates/single_stock.html
  myapp/templates/subtemplate/list_rules.html
  myapp/templates/watchlist.html
  myapp/tests/test_models.py
  myapp/tests/test_scheduler.py
  myapp/tests/test_views.py
  myapp/urls.py
  myapp/views.py
  myrails/settings.py
  requirements.txt
Labels: enhancement

#76 Refactors on buy and sell functionality
  myapp/admin.py
  myapp/exceptions/stock_service.py
  myapp/models.py
  myapp/scheduler/stock_api_update.py
  myapp/views.py
Labels: enhancement

#78 Notifications panel fixes
  myapp/static/js/myapp/base.js
  myapp/templates/base.html
Labels: bug, enhancement, notification feature

#73 Adding Buy and Sell Portfolio Page
  deploy.sh
  myapp/admin.py
  myapp/forms.py
  myapp/migrations/0006_auto_20201115_1228.py
  myapp/migrations/0006_auto_20201126_1314.py
  myapp/migrations/0007_auto_20201123_1920.py
  myapp/migrations/0007_boughtstock_threshold.py
  myapp/models.py
  myapp/scheduler/notification_rules_handler.py
  myapp/scheduler/scheduler.py
  myapp/scheduler/stock_api_update.py
  myapp/scheduler/tests/__init__.py
  myapp/scheduler/tests/test_notification_handler_updater.py
  myapp/scheduler/tests/test_scheduler.py
  myapp/scheduler/tests/test_stock_api_update.py
  myapp/static/css/main.css
  myapp/static/js/myapp/base.js
  myapp/static/js/myapp/buy_model.js
  myapp/static/js/myapp/sell_model.js
  myapp/static/js/myapp/single_stock.js
  myapp/stock_api.py
  myapp/sub_models/__init__.py
  myapp/sub_models/notification_rules_models.py
  myapp/sub_models/tests/__init__.py
  myapp/sub_models/tests/test_models.py
  myapp/templates/add_rule.html
  myapp/templates/base.html
  myapp/templates/edit_rule.html
  myapp/templates/portfolio.html
  myapp/templates/single_stock.html
  myapp/templates/subtemplate/buy_model.html
  myapp/templates/subtemplate/list_rules.html
  myapp/templates/subtemplate/sell_model.html
  myapp/templates/watchlist.html
  myapp/tests/test_models.py
  myapp/tests/test_scheduler.py
  myapp/tests/test_views.py
  myapp/urls.py
  myapp/views.py
  myrails/configuration/Readme.md
  myrails/configuration/prod.encrypted
  myrails/configuration/public_key.pem
  myrails/settings.py
  requirements.txt
Labels: enhancement

#68 Buy and sell task
  myapp/admin.py
  myapp/exceptions/stock_service.py
  myapp/migrations/0006_auto_20201115_1228.py
  myapp/migrations/0006_auto_20201126_1314.py
  myapp/migrations/0006_notification.py
  myapp/migrations/0007_auto_20201114_1423.py
  myapp/migrations/0007_boughtstock_threshold.py
  myapp/migrations/0007_notification_link.py
  myapp/migrations/0008_auto_20201114_1533.py
  myapp/migrations/0008_auto_20201114_2036.py
  myapp/migrations/0009_merge_20201115_1444.py
  myapp/migrations/0009_notification_is_read.py
  myapp/migrations/0010_auto_20201115_1521.py
  myapp/migrations/0010_merge_20201117_1547.py
  myapp/migrations/0011_merge_20201115_2020.py
  myapp/migrations/0012_merge_20201117_1557.py
  myapp/migrations/0013_auto_20201117_1557.py
  myapp/migrations/0014_delete_activityperiodrule.py
  myapp/migrations/0015_auto_20201118_1118.py
  myapp/migrations/0016_recommendationanalystrule_recommenders_percentage.py
  myapp/migrations/0017_auto_20201118_1505.py
  myapp/migrations/0018_auto_20201118_1533.py
  myapp/migrations/0019_auto_20201118_1824.py
  myapp/migrations/0020_auto_20201122_1725.py
  myapp/models.py
  myapp/scheduler/stock_api_update.py
  myapp/static/css/main.css
  myapp/static/js/myapp/buy_model.js
  myapp/static/js/myapp/sell_model.js
  myapp/static/js/myapp/single_stock.js
  myapp/templates/base.html
  myapp/templates/portfolio.html
  myapp/templates/single_stock.html
  myapp/templates/subtemplate/buy_model.html
  myapp/templates/subtemplate/sell_model.html
  myapp/tests/test_models.py
  myapp/tests/test_views.py
  myapp/urls.py
  myapp/views.py
  myrails/settings.py
  requirements.txt
Labels: enhancement

#79 Adding Custom Logo and About Page
  myapp/static/js/myapp/base.js
  myapp/static/logo.png
  myapp/static/logo_large.svg
  myapp/static/logo_nav.svg
  myapp/templates/about.html
  myapp/templates/base.html
  myapp/urls.py
  myapp/views.py
Labels: enhancement
